// Copyright 2026 Oddbit (https://oddbit.id)
// SPDX-License-Identifier: Apache-2.0
//
// Generated by scripts/generate-migrations.ts from migrations/*.sql: do not edit.
// Run `yarn build` (or `yarn migrations:bundle`) after changing a migration.
// The vitest suite fails when this file and the SQL files disagree.

export interface BundledMigration {
  /** File name as wrangler records it in d1_migrations.name. */
  readonly name: string;
  /** The file's statements, split at statement boundaries, comments removed. */
  readonly statements: readonly string[];
}

export const MIGRATIONS: readonly BundledMigration[] = [
  {
    name: "0001_initial.sql",
    statements: [
      `CREATE TABLE links (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  url         TEXT NOT NULL,
  label       TEXT,
  created_at  INTEGER NOT NULL,
  expires_at  INTEGER,
  created_via TEXT DEFAULT 'app',
  created_by  TEXT DEFAULT 'anonymous'
)`,
      `CREATE TABLE slugs (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  link_id     INTEGER NOT NULL REFERENCES links(id) ON DELETE CASCADE,
  slug        TEXT NOT NULL UNIQUE,
  is_custom   INTEGER NOT NULL DEFAULT 0,
  is_primary  INTEGER NOT NULL DEFAULT 0,
  created_at  INTEGER NOT NULL,
  disabled_at INTEGER
)`,
      `CREATE INDEX idx_slugs_slug ON slugs(slug)`,
      `CREATE INDEX idx_slugs_link_id ON slugs(link_id)`,
      `CREATE TABLE clicks (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  slug_id     INTEGER NOT NULL REFERENCES slugs(id) ON DELETE CASCADE,
  clicked_at  INTEGER NOT NULL,
  referrer    TEXT,
  country     TEXT,
  device_type TEXT,
  browser     TEXT,
  channel     TEXT DEFAULT 'direct'
)`,
      `CREATE INDEX idx_clicks_slug_id ON clicks(slug_id)`,
      `CREATE INDEX idx_clicks_clicked_at ON clicks(clicked_at)`,
      `CREATE INDEX idx_clicks_country ON clicks(country)`,
      `CREATE TABLE settings (
  identity TEXT NOT NULL,
  key      TEXT NOT NULL,
  value    TEXT NOT NULL,
  PRIMARY KEY (identity, key)
)`,
      `INSERT INTO settings (identity, key, value) VALUES ('anonymous', 'slug_default_length', '3')`,
      `CREATE TABLE api_keys (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  title        TEXT NOT NULL,
  key_prefix   TEXT NOT NULL,
  key_hash     TEXT NOT NULL UNIQUE,
  scope        TEXT NOT NULL,
  created_at   INTEGER NOT NULL,
  last_used_at INTEGER,
  identity     TEXT NOT NULL DEFAULT 'anonymous'
)`,
      `CREATE INDEX idx_api_keys_hash ON api_keys(key_hash)`,
      `CREATE INDEX idx_api_keys_identity ON api_keys(identity)`,
    ],
  },
  {
    name: "0002_analytics_schema.sql",
    statements: [
      `ALTER TABLE clicks RENAME COLUMN channel TO link_mode`,
      `UPDATE clicks SET link_mode = 'link' WHERE link_mode = 'direct'`,
      `ALTER TABLE clicks ADD COLUMN channel TEXT`,
      `ALTER TABLE clicks ADD COLUMN referrer_host TEXT`,
      `ALTER TABLE clicks ADD COLUMN os TEXT`,
      `ALTER TABLE clicks ADD COLUMN utm_source TEXT`,
      `ALTER TABLE clicks ADD COLUMN utm_medium TEXT`,
      `ALTER TABLE clicks ADD COLUMN utm_campaign TEXT`,
      `ALTER TABLE clicks ADD COLUMN utm_term TEXT`,
      `ALTER TABLE clicks ADD COLUMN utm_content TEXT`,
      `ALTER TABLE clicks ADD COLUMN region TEXT`,
      `ALTER TABLE clicks ADD COLUMN city TEXT`,
      `ALTER TABLE clicks ADD COLUMN language TEXT`,
      `ALTER TABLE clicks ADD COLUMN user_agent TEXT`,
      `ALTER TABLE clicks ADD COLUMN is_bot INTEGER DEFAULT 0`,
      `CREATE INDEX idx_clicks_link_mode ON clicks(link_mode)`,
      `CREATE INDEX idx_clicks_referrer_host ON clicks(referrer_host)`,
      `CREATE INDEX idx_clicks_os ON clicks(os)`,
    ],
  },
  {
    name: "0003_drop_cached_counters.sql",
    statements: [
      `SELECT 1`,
    ],
  },
  {
    name: "0004_slug_text_pk.sql",
    statements: [
      `CREATE TABLE clicks_backup AS
SELECT c.id, s.slug AS slug, c.clicked_at, c.referrer, c.referrer_host,
       c.country, c.region, c.city, c.device_type, c.os, c.browser,
       c.language, c.link_mode, c.channel,
       c.utm_source, c.utm_medium, c.utm_campaign, c.utm_term, c.utm_content,
       c.user_agent, c.is_bot
FROM clicks c
JOIN slugs s ON s.id = c.slug_id`,
      `DROP TABLE clicks`,
      `CREATE TABLE slugs_new (
  link_id     INTEGER NOT NULL REFERENCES links(id) ON DELETE CASCADE,
  slug        TEXT NOT NULL PRIMARY KEY,
  is_custom   INTEGER NOT NULL DEFAULT 0,
  is_primary  INTEGER NOT NULL DEFAULT 0,
  created_at  INTEGER NOT NULL,
  disabled_at INTEGER
)`,
      `INSERT INTO slugs_new (link_id, slug, is_custom, is_primary, created_at, disabled_at)
SELECT link_id, slug, is_custom, is_primary, created_at, disabled_at FROM slugs`,
      `DROP TABLE slugs`,
      `ALTER TABLE slugs_new RENAME TO slugs`,
      `CREATE INDEX idx_slugs_link_id ON slugs(link_id)`,
      `CREATE TABLE clicks (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  slug         TEXT NOT NULL REFERENCES slugs(slug) ON DELETE CASCADE,
  clicked_at   INTEGER NOT NULL,
  referrer     TEXT,
  referrer_host TEXT,
  country      TEXT,
  region       TEXT,
  city         TEXT,
  device_type  TEXT,
  os           TEXT,
  browser      TEXT,
  language     TEXT,
  link_mode    TEXT DEFAULT 'link',
  channel      TEXT,
  utm_source   TEXT,
  utm_medium   TEXT,
  utm_campaign TEXT,
  utm_term     TEXT,
  utm_content  TEXT,
  user_agent   TEXT,
  is_bot       INTEGER DEFAULT 0
)`,
      `INSERT INTO clicks (id, slug, clicked_at, referrer, referrer_host, country, region, city, device_type, os, browser, language, link_mode, channel, utm_source, utm_medium, utm_campaign, utm_term, utm_content, user_agent, is_bot)
SELECT id, slug, clicked_at, referrer, referrer_host, country, region, city, device_type, os, browser, language, link_mode, channel, utm_source, utm_medium, utm_campaign, utm_term, utm_content, user_agent, is_bot
FROM clicks_backup`,
      `DROP TABLE clicks_backup`,
      `CREATE INDEX idx_clicks_slug ON clicks(slug)`,
      `CREATE INDEX idx_clicks_clicked_at ON clicks(clicked_at)`,
      `CREATE INDEX idx_clicks_country ON clicks(country)`,
      `CREATE INDEX idx_clicks_link_mode ON clicks(link_mode)`,
      `CREATE INDEX idx_clicks_referrer_host ON clicks(referrer_host)`,
      `CREATE INDEX idx_clicks_os ON clicks(os)`,
    ],
  },
  {
    name: "0005_bundles.sql",
    statements: [
      `CREATE TABLE bundles (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  name        TEXT NOT NULL,
  description TEXT,
  icon        TEXT,
  accent      TEXT NOT NULL DEFAULT 'orange' CHECK (accent IN ('orange','red','green','blue','purple')),
  archived_at INTEGER,
  created_via TEXT DEFAULT 'app',
  created_by  TEXT NOT NULL,
  created_at  INTEGER NOT NULL,
  updated_at  INTEGER NOT NULL
)`,
      `CREATE INDEX idx_bundles_created_by ON bundles(created_by)`,
      `CREATE INDEX idx_bundles_archived_at ON bundles(archived_at)`,
      `CREATE TABLE bundle_links (
  bundle_id INTEGER NOT NULL REFERENCES bundles(id) ON DELETE CASCADE,
  link_id   INTEGER NOT NULL REFERENCES links(id)   ON DELETE CASCADE,
  added_at  INTEGER NOT NULL,
  PRIMARY KEY (bundle_id, link_id)
)`,
      `CREATE INDEX idx_bundle_links_link_id ON bundle_links(link_id)`,
      `ALTER TABLE clicks ADD COLUMN visitor_fp TEXT`,
      `CREATE INDEX idx_clicks_visitor_fp ON clicks(visitor_fp)`,
    ],
  },
  {
    name: "0006_self_referrer_flag.sql",
    statements: [
      `ALTER TABLE clicks ADD COLUMN is_self_referrer INTEGER DEFAULT 0`,
      `CREATE INDEX idx_clicks_is_self_referrer ON clicks(is_self_referrer)`,
    ],
  },
  {
    name: "0007_links_created_at_index.sql",
    statements: [
      `CREATE INDEX idx_links_created_at ON links(created_at DESC, id DESC)`,
    ],
  },
];

/** Name of the last migration: the schema this build expects to find applied. */
export const SCHEMA_VERSION = "0007_links_created_at_index.sql";
