// Copyright 2026 Oddbit (https://oddbit.id)
// SPDX-License-Identifier: Apache-2.0

/**
 * Renders migrations/*.sql into the TypeScript module the Worker boots from.
 *
 * Pure: takes file names and contents, returns source text. The file system
 * side lives in generate-migrations.ts so this half can run inside the
 * vitest pool, where the drift test compares its output with the committed
 * module byte for byte.
 *
 * Each migration is split into single statements here, at build time, with
 * the same scanner the tests exercise. The Worker then hands D1 a list of
 * prepared statements and never parses SQL at a cold start.
 */

import { splitSqlStatements, SqlSplitError } from "../src/db/sql-split";

export interface MigrationFile {
  name: string;
  sql: string;
}

const NAME_PATTERN = /^[^/\\]+\.sql$/;

/** Escapes text for use inside a template literal, so the SQL round-trips exactly. */
function templateLiteral(text: string): string {
  return "`" + text.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${") + "`";
}

export function renderMigrationsModule(files: readonly MigrationFile[]): string {
  if (files.length === 0) throw new Error("No migrations found: the migrations directory holds no .sql files.");
  for (const file of files) {
    if (!NAME_PATTERN.test(file.name)) throw new Error(`${file.name} is not a .sql migration file.`);
  }

  const sorted = [...files].sort((a, b) => a.name.localeCompare(b.name));
  const entries = sorted.map((file) => {
    let statements: string[];
    try {
      statements = splitSqlStatements(file.sql);
    } catch (err) {
      const reason = err instanceof SqlSplitError ? err.message : String(err);
      throw new Error(`${file.name}: ${reason}`);
    }
    const body = statements.map((s) => `      ${templateLiteral(s)},`).join("\n");
    return `  {\n    name: ${JSON.stringify(file.name)},\n    statements: [\n${body}\n    ],\n  },`;
  });

  const last = sorted[sorted.length - 1].name;

  return `// Copyright 2026 Oddbit (https://oddbit.id)
// SPDX-License-Identifier: Apache-2.0
//
// Generated by scripts/generate-migrations.ts from migrations/*.sql: do not edit.
// Run \`yarn build\` (or \`yarn migrations:bundle\`) after changing a migration.
// The vitest suite fails when this file and the SQL files disagree.

export interface BundledMigration {
  /** File name as wrangler records it in d1_migrations.name. */
  readonly name: string;
  /** The file's statements, split at statement boundaries, comments removed. */
  readonly statements: readonly string[];
}

export const MIGRATIONS: readonly BundledMigration[] = [
${entries.join("\n")}
];

/** Name of the last migration: the schema this build expects to find applied. */
export const SCHEMA_VERSION = ${JSON.stringify(last)};
`;
}
